export const ShopRoute = '/shop'
export const HomeRoute = '/'
export const RegisterRoute = '/register'
export const AuthRoute = '/authentication'
export const NewsRoute = '/news' 
export const CourseRoute = '/course'
export const ContactRoute = '/contact'
export const LOCAL_API_URL = 'https://videokat-server-production.up.railway.app/api'